#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-mdurl
Version  : 0.1.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/36/c5/00f7f9e5b53dcf44f8806201e69016b64ade1075f38ab5d4e8f5ab4b5bfb/mdurl-0.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/36/c5/00f7f9e5b53dcf44f8806201e69016b64ade1075f38ab5d4e8f5ab4b5bfb/mdurl-0.1.0.tar.gz
Summary  : Markdown URL utilities
Group    : Development/Tools
License  : MIT
Requires: pypi-mdurl-license = %{version}-%{release}
Requires: pypi-mdurl-python = %{version}-%{release}
Requires: pypi-mdurl-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)

%description
# mdurl
[![Build Status](https://github.com/hukkin/mdurl/workflows/Tests/badge.svg?branch=master)](https://github.com/hukkin/mdurl/actions?query=workflow%3ATests+branch%3Amaster+event%3Apush)
[![codecov.io](https://codecov.io/gh/hukkin/mdurl/branch/master/graph/badge.svg)](https://codecov.io/gh/hukkin/mdurl)
[![PyPI version](https://img.shields.io/pypi/v/mdurl)](https://pypi.org/project/mdurl)

%package license
Summary: license components for the pypi-mdurl package.
Group: Default

%description license
license components for the pypi-mdurl package.


%package python
Summary: python components for the pypi-mdurl package.
Group: Default
Requires: pypi-mdurl-python3 = %{version}-%{release}

%description python
python components for the pypi-mdurl package.


%package python3
Summary: python3 components for the pypi-mdurl package.
Group: Default
Requires: python3-core
Provides: pypi(mdurl)

%description python3
python3 components for the pypi-mdurl package.


%prep
%setup -q -n mdurl-0.1.0
cd %{_builddir}/mdurl-0.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1638563887
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mdurl
cp %{_builddir}/mdurl-0.1.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdurl/b87bd47e069fa27d2243d1638d435a9d5081ccff
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mdurl/b87bd47e069fa27d2243d1638d435a9d5081ccff

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
